### ISSUE TITLE
Just a question...

### ISSUE THREAD

**Issue by Korte68** [matt8707/kiosk-mode#1]
I have a few page in the menu, and a few of them should be available in kiosk mode. is it possible?

**Comment by KTibow** [comment]
Nope without adding some more features, try out card-mod theming for this.

**Comment by matt8707** [comment]
* Just add `?kiosk` to whatever page you want
* If you're navigating across dashboards you need to refresh the page for it to take effect
* card-mod can only hide the header since the sidebar drawer is outside the scope of card-mod-root
* If you're talking about views, the tabs along the header will be hidden. But you can still navigate them

![tabs](https://user-images.githubusercontent.com/36163594/95924946-e0b47b00-0db8-11eb-94c6-0d854314b7b7.png)

**Comment by KTibow** [comment]
I think @Korte68 wants to hide specific tabs.

**Comment by matt8707** [comment]
But, why. All tabs are hidden, that's the point. Hiding specific tabs are built in
https://www.home-assistant.io/lovelace/dashboards-and-views/#visible

**Comment by KTibow** [comment]
In your case you should probably make a new account @Korte68.

**Comment by Korte68** [comment]
Thank you. I am looking for a solution to substitute Compact-custom (https://maykar.github.io/custom-header/#intro/intro).
