### ISSUE TITLE
swaping between pages  

### ISSUE THREAD

**Issue by livewild1988** [matt8707/kiosk-mode#2]
hello i have my ui set up in buttons navigating to pages (path: devices, path: rooms etc) your instructions say add path: kiosk but i dont work when you have a path already, also swapping between lovelace  ui's drops   ?kiosk even though i have added this to the navigation link. if i hit refresh it will go into kiosk but not working for me as i can see.

thanks chris

**Comment by KTibow** [comment]
can you please use capitalization because its really hard also please use punctuation and markdown code formatting

**Comment by livewild1988** [comment]
Hello
Sorry i have managed to sort the problem with swapping between Lovelace's, I have just put it all on one, and added ?kiosk to every button navigation, this has worked.
My new problem is I use a background image and I have now got a white bar at the bottom of the page 
![Capture_100](https://user-images.githubusercontent.com/43131951/96368359-5c148480-114b-11eb-9f6a-a42b3644310d.PNG)

**Comment by KTibow** [comment]
Try reading the last posts (maybe 20-50) in this thread: https://community.home-assistant.io/t/card-mod-super-charge-your-themes/212176/307

**Comment by livewild1988** [comment]
Sorry what am i looking for on that for, card mod?
I dint have a problem with the custom header card but its been removed now.
Thanks for your help 
Chris

**Comment by KTibow** [comment]
Other people in that thread have experienced that problem because they have tried to hide the header.

**Comment by GregHKI** [comment]
I modified mine to leave the tabs up top. ?kiosk removes all, ?nesthub leaves in the tabs
`if (window.location.href.indexOf('nesthub') > 0) {
    setTimeout(function() {
        try {
            const home_assistant_main = document
                .querySelector("body > home-assistant").shadowRoot
                .querySelector("home-assistant-main");

            const header = home_assistant_main.shadowRoot
                .querySelector("app-drawer-layout > partial-panel-resolver > ha-panel-lovelace").shadowRoot
                .querySelector("hui-root").shadowRoot
                .querySelector("#layout > app-header > app-toolbar")
                .style.display = "none";
				

            const drawer = home_assistant_main.shadowRoot
                .querySelector("#drawer")
                .style.display = 'none';

            home_assistant_main.style.setProperty("--app-drawer-width", 0);
            home_assistant_main.shadowRoot
                .querySelector("#drawer > ha-sidebar").shadowRoot
                .querySelector("div.menu")
                .click();
            window.dispatchEvent(new Event('resize'));
        } 
        catch (e) {
            console.log(e);
        }
    }, 200);
}`

**Comment by lordgreggreg** [comment]
I modified mine to leave in the header if I do ?nesthub instead of kiosk by adding this code to kiosk-mode.js
`if (window.location.href.indexOf('nesthub') > 0) {`
`    setTimeout(function() {`
`        try {`
`            const home_assistant_main = document`
`                .querySelector("body > home-assistant").shadowRoot`
`                .querySelector("home-assistant-main");`
``
`            const header = home_assistant_main.shadowRoot`
`                .querySelector("app-drawer-layout > partial-panel-resolver > ha-panel-lovelace").shadowRoot`
`                .querySelector("hui-root").shadowRoot`
`                .querySelector("#layout > app-header > app-toolbar")`
`                .style.display = "none";`
`				`
``
`            const drawer = home_assistant_main.shadowRoot`
`                .querySelector("#drawer")`
`                .style.display = 'none';`
``
`            home_assistant_main.style.setProperty("--app-drawer-width", 0);`
`            home_assistant_main.shadowRoot`
`                .querySelector("#drawer > ha-sidebar").shadowRoot`
`                .querySelector("div.menu")`
`                .click();`
`            window.dispatchEvent(new Event('resize'));`
`        } `
`        catch (e) {`
`            console.log(e);`
`        }`
`    }, 200);`
`}`

**Comment by KTibow** [comment]
Can you close this?
